menu:
    Blog: /
    Archive: /archives/
    About: /about/
    X: https://x.com/a_hwon
    GitHub: https://github.com/hhwon
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: seansun
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2016
